import { Activity, ShieldCheck, UserCheck, Baby, HeartPulse, Users } from "lucide-react";

export const PHONE = "0758867235";
export const WHATSAPP = "254758867235";
export const EMAIL = "catecos924@gmail.com";
export const YOUTUBE = "https://www.youtube.com/@CateCos-u1f";
export const LOCATION = "Utawala, Nairobi, Kenya";

export const SERVICES = [
  {
    id: "home-nursing",
    title: "Home Nursing Care",
    icon: Activity,
    shortDesc: "Professional nurses at your doorstep 24/7.",
    description: `Our Home Nursing Care service brings the full expertise of a clinical nurse right into your home. Whether you or your loved one needs daily monitoring of vital signs, IV medication administration, catheter care, or simply a professional to manage complex health conditions, our nurses are equipped and ready.\n\nWe assess each patient individually, create a personalised care plan, and ensure consistent follow-up with attending physicians. Our goal is to create a healing environment within the comfort of familiar surroundings — reducing hospital readmissions and improving quality of life significantly.`,
    highlights: [
      "Daily vital signs monitoring",
      "IV therapy & medication administration",
      "Catheter and stoma care",
      "Patient education and family training",
      "Physician coordination and reporting",
      "24/7 emergency support",
    ],
    images: ["/images/home-nursing-1.png", "/images/home-nursing-2.png"],
    color: "from-teal-500/20 to-green-500/20",
  },
  {
    id: "post-operative",
    title: "Post-Operative Care",
    icon: ShieldCheck,
    shortDesc: "Expert recovery support after surgery.",
    description: `Recovery after surgery is a critical phase. Our Post-Operative Care service ensures patients transition safely from hospital to home with the professional support they need. Our nurses follow surgeon-prescribed protocols precisely, monitoring for complications and helping manage pain effectively.\n\nWe provide comprehensive wound care, drainage management, mobility assistance, and early detection of post-surgical complications. This reduces the risk of hospital readmission and accelerates the healing journey, all from the comfort and privacy of your own home in Utawala, Nairobi.`,
    highlights: [
      "Wound care and dressing changes",
      "Drain and tube management",
      "Pain assessment and management",
      "Post-op mobility assistance",
      "Complication monitoring and prevention",
      "Surgeon follow-up coordination",
    ],
    images: ["/images/postop-1.png", "/images/postop-2.png"],
    color: "from-blue-500/20 to-teal-500/20",
  },
  {
    id: "elderly-care",
    title: "Elderly Care",
    icon: UserCheck,
    shortDesc: "Compassionate dignified care for seniors.",
    description: `Our Elderly Care service is designed with deep respect for the dignity, independence, and joy of senior living. We understand that aging brings unique challenges, and our caregivers are specially trained in geriatric care to meet those needs with patience, warmth, and clinical expertise.\n\nFrom helping with daily activities, managing chronic conditions, fall prevention, memory care, to providing meaningful companionship — our carers become trusted members of your family. We work closely with families to ensure your elderly loved ones remain engaged, comfortable, and medically safe at home.`,
    highlights: [
      "Daily activities assistance (bathing, grooming, feeding)",
      "Chronic disease monitoring",
      "Fall prevention strategies",
      "Dementia and memory care support",
      "Companionship and emotional wellbeing",
      "Family training and respite care",
    ],
    images: ["/images/elderly-1.png", "/images/elderly-2.png"],
    color: "from-amber-500/20 to-orange-500/20",
  },
  {
    id: "maternal-newborn",
    title: "Maternal & Newborn Care",
    icon: Baby,
    shortDesc: "Expert support for mothers and newborns.",
    description: `Welcoming a new baby is one of life's most beautiful moments — and also one of the most demanding. Our Maternal & Newborn Care service supports new mothers through the postpartum journey with clinically-trained midwives and nurses who visit your home.\n\nWe provide breastfeeding support, baby bathing demonstrations, newborn assessments, umbilical cord care, postpartum recovery monitoring, and emotional support for new mothers. We also screen for postpartum depression and connect families to the support they need. Our nurses take the time to ensure both mother and baby are thriving.`,
    highlights: [
      "Breastfeeding guidance and lactation support",
      "Newborn assessment and weight monitoring",
      "Umbilical cord and circumcision care",
      "Postpartum recovery monitoring",
      "Postpartum depression screening",
      "Baby bathing and hygiene education",
    ],
    images: ["/images/maternal-1.png", "/images/maternal-2.png"],
    color: "from-pink-500/20 to-rose-500/20",
  },
  {
    id: "wound-dressing",
    title: "Wound Dressing",
    icon: HeartPulse,
    shortDesc: "Professional sterile wound management at home.",
    description: `Proper wound care is essential to prevent infections, reduce healing time, and avoid complications. Our professional Wound Dressing service brings clinical-grade wound management directly to your home in Utawala, Nairobi and surrounding areas.\n\nOur nurses use evidence-based wound care protocols, sterile techniques, and modern dressing materials to manage surgical wounds, diabetic ulcers, pressure sores, burns, and traumatic wounds. We document wound progress, communicate with your physician, and adjust care plans as healing progresses — ensuring the best possible outcomes.`,
    highlights: [
      "Surgical wound care and dressing changes",
      "Diabetic wound and ulcer management",
      "Pressure sore prevention and treatment",
      "Burns care and dressing",
      "Wound assessment and photography",
      "Infection prevention and monitoring",
    ],
    images: ["/images/wound-1.png", "/images/wound-2.png"],
    color: "from-green-500/20 to-emerald-500/20",
  },
  {
    id: "chronic-disease",
    title: "Chronic Disease Management",
    icon: Activity,
    shortDesc: "Ongoing professional care for chronic conditions.",
    description: `Living with a chronic condition like diabetes, hypertension, heart failure, COPD, or kidney disease requires consistent professional monitoring and management. Our Chronic Disease Management service brings this expert ongoing care to your home.\n\nOur nurses work closely with your specialist physicians to monitor key health parameters, manage medications, and educate patients and families on lifestyle adjustments. We help prevent dangerous complications, reduce emergency visits, and improve the day-to-day quality of life for patients managing long-term health conditions across Nairobi.`,
    highlights: [
      "Blood sugar monitoring for diabetics",
      "Blood pressure monitoring and management",
      "Medication adherence support",
      "Dietary guidance and lifestyle education",
      "Lab coordination and physician reporting",
      "Emergency response planning",
    ],
    images: ["/images/chronic-1.png", "/images/chronic-2.png"],
    color: "from-purple-500/20 to-indigo-500/20",
  },
  {
    id: "nurse-recruitment",
    title: "Nurse Recruitment",
    icon: Users,
    shortDesc: "Placing qualified nurses for your institution.",
    description: `Catecos Nursing Hub is also a trusted nursing recruitment agency, connecting healthcare institutions, hospitals, clinics, and private households with highly qualified and vetted nursing professionals across Kenya.\n\nWe maintain a database of registered nurses with diverse specialisations. All candidates undergo thorough background checks, credential verification, skills assessment, and professional reference checks before placement. Whether you need a short-term cover, a permanent home caregiver, or a specialised ICU/theatre nurse, we have the talent to meet your needs swiftly and reliably.`,
    highlights: [
      "Registered nurses for hospitals and clinics",
      "Home caregivers for private families",
      "Specialised nurses (ICU, Theatre, Paediatrics)",
      "Background checks and credential verification",
      "Short-term, long-term and permanent placements",
      "Nursing staffing consultancy",
    ],
    images: ["/images/recruitment-1.png", "/images/recruitment-2.png"],
    color: "from-cyan-500/20 to-blue-500/20",
  },
];

export const TEAM = [
  {
    name: "Catherine Wanjiru",
    role: "Founder & Lead Nurse",
    bio: "Registered Nurse with 12+ years of clinical and home care experience. Passionate about accessible, compassionate healthcare.",
    image: "/images/elderly-1.png",
    credentials: "RN, BSN",
  },
  {
    name: "James Omondi",
    role: "Senior Home Care Nurse",
    bio: "Specialises in post-operative recovery and wound management. Known for precision, patience, and a warm bedside manner.",
    image: "/images/home-nursing-1.png",
    credentials: "RN, Wound Care Certified",
  },
  {
    name: "Grace Njeri",
    role: "Maternal & Newborn Specialist",
    bio: "Registered Midwife with expertise in postnatal care and infant health. Trusted by hundreds of new mothers across Nairobi.",
    image: "/images/maternal-1.png",
    credentials: "RM, BSN",
  },
  {
    name: "Peter Kimani",
    role: "Elderly Care Specialist",
    bio: "Geriatric care expert dedicated to improving the quality of life for senior patients through personalised, dignified care.",
    image: "/images/elderly-2.png",
    credentials: "RN, Geriatric Care Cert.",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "5 Signs Your Loved One May Need Home Nursing Care",
    excerpt: "Recognising when a family member needs professional nursing support at home can be challenging. Here are the key signs to watch for.",
    category: "Care Tips",
    date: "March 20, 2025",
    readTime: "4 min read",
    image: "/images/elderly-1.png",
    content: `Caring for an aging parent or recovering family member is a labour of love — but there are moments when professional support becomes essential. Here are five clear signs that home nursing care may be needed.\n\n1. Frequent falls or balance problems — if your loved one is falling more often, a professional nurse can assess safety risks and implement fall-prevention measures.\n\n2. Difficulty managing medications — missing doses or confusing medications can be dangerous. A home nurse ensures proper medication adherence.\n\n3. Worsening chronic conditions — conditions like diabetes, hypertension, or heart disease require consistent monitoring. Home nurses can track vitals and report changes early.\n\n4. Post-hospital recovery — the period immediately after discharge is critical. Nurses ensure proper wound care, mobility, and nutrition.\n\n5. Caregiver burnout — when family caregivers are exhausted, professional support ensures consistent quality care while giving families needed rest.`,
  },
  {
    id: 2,
    title: "What to Expect from Post-Operative Home Care",
    excerpt: "Coming home after surgery can feel overwhelming. Our guide helps you understand what professional post-op care looks like and why it matters.",
    category: "Recovery",
    date: "March 5, 2025",
    readTime: "5 min read",
    image: "/images/postop-1.png",
    content: `Leaving the hospital after surgery is a major milestone — but recovery at home requires careful attention. Professional post-operative home care makes a significant difference in outcomes.\n\nWhat our post-op nurses do:\n\nWound management — sterile dressing changes and infection monitoring are critical in the first two weeks. Our nurses follow your surgeon's exact protocols.\n\nPain monitoring — we assess your pain levels, ensure you're taking the right medications at the right times, and communicate concerns to your medical team immediately.\n\nMobility support — early, guided mobility prevents complications like blood clots. Our nurses assist safely with movement exercises.\n\nNutrition guidance — proper nutrition accelerates healing. We advise on foods that support tissue repair and immune function.\n\nEmotional support — recovery can be isolating. Having a caring, professional presence at home significantly improves patient morale and outcomes.`,
  },
  {
    id: 3,
    title: "Managing Diabetes at Home: A Comprehensive Guide",
    excerpt: "Diabetes management requires daily discipline. Learn how home nursing support can help you keep blood sugar stable and complications at bay.",
    category: "Health Tips",
    date: "February 18, 2025",
    readTime: "6 min read",
    image: "/images/chronic-1.png",
    content: `Diabetes affects millions of Kenyans and requires consistent daily management to prevent serious complications like kidney disease, blindness, and limb amputations. Here's how proper home care can help.\n\nBlood sugar monitoring — regular monitoring helps identify dangerous highs and lows before they become emergencies. Our nurses perform structured monitoring and maintain detailed logs for your physician.\n\nMedication management — insulin administration, oral medication timing, and drug interactions all require professional oversight. We ensure you never miss a dose.\n\nFoot care — diabetic foot complications are a leading cause of amputation. Our nurses perform thorough foot inspections and wound care at every visit.\n\nDiet and lifestyle — we provide personalised dietary guidance, helping you understand which foods affect your blood sugar and how to make sustainable lifestyle changes.\n\nEmergency preparedness — we create an emergency action plan and ensure both patients and families know how to respond to hypoglycaemic or hyperglycaemic episodes.`,
  },
  {
    id: 4,
    title: "Breastfeeding Support: How a Maternal Nurse Can Help",
    excerpt: "Breastfeeding is natural but not always easy. A trained maternal nurse can make all the difference for new mothers in the early weeks.",
    category: "Maternal Health",
    date: "January 30, 2025",
    readTime: "4 min read",
    image: "/images/maternal-1.png",
    content: `Breastfeeding is one of the best things a mother can do for her baby, but many new mothers struggle in the early days. A trained maternal nurse at home makes a huge difference.\n\nProper latch technique — an incorrect latch causes pain and reduces milk transfer. Our midwives demonstrate and practice correct positioning until you feel confident.\n\nMilk supply concerns — many mothers worry their supply isn't enough. We assess feeding frequency, baby's output, and weight gain to give you accurate reassurance or targeted solutions.\n\nEngorgement and mastitis — painful breast conditions are common in the early weeks. Nurses can treat engorgement, teach proper drainage techniques, and identify early signs of infection.\n\nPostpartum recovery monitoring — we track your physical and emotional recovery, screening for postpartum depression and connecting you to support if needed.\n\nNewborn assessments — we monitor your baby's weight, feeding patterns, jaundice levels, and developmental milestones, giving you peace of mind that your baby is thriving.`,
  },
];
